/**
 * @file DjangoAdapter — Django 框架端點偵測 Adapter
 * @description Sprint 24 — 偵測 Django / Django REST Framework 端點，
 *   繼承 PythonBaseAdapter，chain building 沿用 heuristic Python chains。
 *
 * 支援的路由模式：
 *   - `path('url/', view_func)` — Django URL patterns
 *   - `re_path(r'^url/$', view_func)` — Django regex URL patterns
 *   - `include('app.urls')` — nested URL configs (route group prefix)
 *   - `@api_view(['GET', 'POST'])` — DRF function-based views
 *   - `class XxxViewSet(viewsets.ModelViewSet)` — DRF ViewSet (auto CRUD)
 *   - `XxxView.as_view()` — class-based views in urlpatterns
 */

import { PythonBaseAdapter } from './python-base-adapter.js';
import type { AdapterContext, FrameworkDetection } from './types.js';
import type { AnalysisResult, GraphNode } from '../../types.js';
import type { ApiEndpoint, HttpMethod } from '../endpoint-detector.js';

// ---------------------------------------------------------------------------
// Regex patterns — Django URL patterns
// ---------------------------------------------------------------------------

/**
 * Matches `path('url/', view, ...)` in urlpatterns.
 *
 * Capture groups:
 *   1. URL path string
 *   2. View reference (function name, or further args)
 */
const DJANGO_PATH_RE = /\bpath\(\s*['"]([^'"]*)['"]\s*,\s*([^,)]+)/g;

/**
 * Matches `re_path(r'^url/$', view, ...)` in urlpatterns.
 *
 * Capture groups:
 *   1. Regex URL pattern string (raw or normal)
 *   2. View reference
 */
const DJANGO_RE_PATH_RE = /\bre_path\(\s*r?['"]([^'"]*)['"]\s*,\s*([^,)]+)/g;

/**
 * Matches `include('app.urls')` or `include(('app.urls', 'app'))` in path() calls.
 * Used to detect nested URL configurations with their prefix.
 *
 * Capture groups:
 *   1. URL prefix (from the enclosing path())
 *   2. Included module path
 */
const DJANGO_INCLUDE_RE = /\bpath\(\s*['"]([^'"]*)['"]\s*,\s*include\(\s*['"]([^'"]+)['"]/g;

/**
 * Matches DRF `@api_view(['GET', 'POST'])` decorator.
 *
 * Capture groups:
 *   1. Method list string (e.g. `'GET', 'POST'`)
 */
const DRF_API_VIEW_RE = /@api_view\(\s*\[([^\]]*)\]/g;

/**
 * Matches DRF ViewSet class definitions.
 *
 * Patterns:
 *   - `class UserViewSet(viewsets.ModelViewSet):`
 *   - `class UserViewSet(viewsets.ViewSet):`
 *   - `class UserViewSet(ModelViewSet):`
 *   - `class UserViewSet(ViewSet):`
 *
 * Capture groups:
 *   1. Class name (e.g. `UserViewSet`)
 *   2. Parent class (e.g. `viewsets.ModelViewSet` or `ModelViewSet`)
 */
const DRF_VIEWSET_RE =
  /class\s+(\w+)\s*\(\s*(?:viewsets\.)?(ModelViewSet|ViewSet|ReadOnlyModelViewSet|GenericViewSet)\s*\)/g;

/**
 * Matches `.as_view()` usage in urlpatterns.
 *
 * Capture groups:
 *   1. Class name (e.g. `UserListView`)
 */
const AS_VIEW_RE = /(\w+)\.as_view\(\)/g;

// ---------------------------------------------------------------------------
// ViewSet CRUD mapping
// ---------------------------------------------------------------------------

/** Standard CRUD endpoints generated by ModelViewSet / ReadOnlyModelViewSet */
interface ViewSetCrudEntry {
  method: HttpMethod;
  suffix: string;
  action: string;
}

const MODEL_VIEWSET_CRUD: ViewSetCrudEntry[] = [
  { method: 'GET', suffix: '/', action: 'list' },
  { method: 'POST', suffix: '/', action: 'create' },
  { method: 'GET', suffix: '/:id', action: 'retrieve' },
  { method: 'PUT', suffix: '/:id', action: 'update' },
  { method: 'DELETE', suffix: '/:id', action: 'destroy' },
];

const READONLY_VIEWSET_CRUD: ViewSetCrudEntry[] = [
  { method: 'GET', suffix: '/', action: 'list' },
  { method: 'GET', suffix: '/:id', action: 'retrieve' },
];

const GENERIC_VIEWSET_CRUD: ViewSetCrudEntry[] = [
  { method: 'GET', suffix: '/', action: 'list' },
];

// ---------------------------------------------------------------------------
// DjangoAdapter
// ---------------------------------------------------------------------------

/**
 * Django / Django REST Framework Adapter.
 *
 * - `detect()`: 檢查 requirements.txt / pyproject.toml / setup.py 是否包含
 *   `django` 或 `djangorestframework` 依賴
 * - `extractEndpoints()`: 使用多種 regex 從 Python 檔案中萃取端點：
 *   urlpatterns path() / re_path()、include()、@api_view、ViewSet、as_view()
 * - `buildChains()`: 沿用 PythonBaseAdapter heuristic Python chains
 */
export class DjangoAdapter extends PythonBaseAdapter {
  readonly name = 'django';
  readonly displayName = 'Django';
  readonly language = 'python' as const;

  // -------------------------------------------------------------------------
  // detect
  // -------------------------------------------------------------------------

  /**
   * 偵測目標專案是否使用 Django 或 Django REST Framework。
   *
   * 在 requirements.txt / pyproject.toml / setup.py 中搜尋
   * `django` 或 `djangorestframework` 依賴。
   *
   * @param analysis 分析結果
   * @returns 偵測結果（confidence 1.0），若未偵測到則回傳 `null`
   */
  detect(analysis: AnalysisResult): FrameworkDetection | null {
    const djangoResult = this.detectPythonDependency(analysis, 'django');
    if (djangoResult.found) {
      const version = djangoResult.version ? `@${djangoResult.version}` : '';
      return {
        adapterName: this.name,
        confidence: 1.0,
        evidence: [`found django${version} in ${djangoResult.source}`],
      };
    }

    const drfResult = this.detectPythonDependency(analysis, 'djangorestframework');
    if (drfResult.found) {
      const version = drfResult.version ? `@${drfResult.version}` : '';
      return {
        adapterName: this.name,
        confidence: 1.0,
        evidence: [`found djangorestframework${version} in ${drfResult.source}`],
      };
    }

    return null;
  }

  // -------------------------------------------------------------------------
  // extractEndpoints
  // -------------------------------------------------------------------------

  /**
   * 從分析結果中萃取 Django / DRF API 端點。
   *
   * 遍歷所有 .py 檔案節點，使用多種 regex 偵測：
   *   1. urlpatterns 中的 path() / re_path()
   *   2. include() 巢狀 URL configs（作為路由群組前綴）
   *   3. @api_view decorator
   *   4. ViewSet class 定義（自動產生 CRUD 端點）
   *   5. as_view() class-based views
   *
   * 若 graph 中無 .py 檔案，改用磁碟掃描模式。
   *
   * @param ctx 預處理的分析上下文
   * @returns 端點清單，每個端點的 id 格式為 `${method} ${path}`
   */
  extractEndpoints(ctx: AdapterContext): ApiEndpoint[] {
    const { analysis } = ctx;
    const results: ApiEndpoint[] = [];

    // Collect .py file nodes from the analysis graph
    const pyFileNodes = analysis.graph.nodes.filter(
      (n: GraphNode) => n.type === 'file' && n.filePath.endsWith('.py'),
    );

    if (pyFileNodes.length === 0) {
      // Fallback: disk scan with DRF decorator prefixes
      return this.scanPythonEndpoints(analysis.projectPath, ['router', 'app']);
    }

    // First pass: collect include() prefixes for nested URL resolution
    const includePrefixes = new Map<string, string>();
    for (const fileNode of pyFileNodes) {
      const source = this.readSourceCode(analysis, fileNode);
      if (!source) continue;
      this.extractIncludePrefixes(source, includePrefixes);
    }

    // Second pass: extract all endpoint types
    for (const fileNode of pyFileNodes) {
      const source = this.readSourceCode(analysis, fileNode);
      if (!source) continue;

      // 1. path() URL patterns
      this.extractPathEndpoints(source, fileNode, results);

      // 2. re_path() URL patterns
      this.extractRePathEndpoints(source, fileNode, results);

      // 3. @api_view decorator
      this.extractApiViewEndpoints(source, fileNode, results);

      // 4. ViewSet CRUD endpoints
      this.extractViewSetEndpoints(source, fileNode, results);
    }

    return results;
  }

  // -------------------------------------------------------------------------
  // Private: include() prefix extraction
  // -------------------------------------------------------------------------

  /**
   * 從 source 中提取 include() 巢狀 URL 配置的前綴映射。
   *
   * 解析 `path('api/', include('myapp.urls'))` 中的前綴與模組名稱，
   * 存入 prefixes map 以供後續端點路徑解析使用。
   *
   * @param source 檔案原始碼
   * @param prefixes 前綴映射（模組名稱 -> URL 前綴），就地修改
   */
  private extractIncludePrefixes(
    source: string,
    prefixes: Map<string, string>,
  ): void {
    const includeRe = new RegExp(DJANGO_INCLUDE_RE.source, DJANGO_INCLUDE_RE.flags);
    let match: RegExpExecArray | null;

    while ((match = includeRe.exec(source)) !== null) {
      const urlPrefix = match[1] ?? '';
      const modulePath = match[2] ?? '';
      if (modulePath) {
        prefixes.set(modulePath, urlPrefix);
      }
    }
  }

  // -------------------------------------------------------------------------
  // Private: path() endpoint extraction
  // -------------------------------------------------------------------------

  /**
   * 從 urlpatterns 中提取 path() 定義的端點。
   *
   * @param source 檔案原始碼
   * @param fileNode 檔案 GraphNode
   * @param results 收集端點的目標陣列
   */
  private extractPathEndpoints(
    source: string,
    fileNode: GraphNode,
    results: ApiEndpoint[],
  ): void {
    const pathRe = new RegExp(DJANGO_PATH_RE.source, DJANGO_PATH_RE.flags);
    let match: RegExpExecArray | null;

    while ((match = pathRe.exec(source)) !== null) {
      const urlPath = match[1] ?? '';
      const viewRef = (match[2] ?? '').trim();

      // Skip include() calls — those are handled separately
      if (viewRef.startsWith('include(')) continue;

      const handler = this.extractViewName(viewRef);
      const normalizedPath = this.normalizeDjangoPath(urlPath);

      this.addEndpoint(results, 'GET', normalizedPath, handler, fileNode);
    }
  }

  // -------------------------------------------------------------------------
  // Private: re_path() endpoint extraction
  // -------------------------------------------------------------------------

  /**
   * 從 urlpatterns 中提取 re_path() 定義的端點。
   *
   * @param source 檔案原始碼
   * @param fileNode 檔案 GraphNode
   * @param results 收集端點的目標陣列
   */
  private extractRePathEndpoints(
    source: string,
    fileNode: GraphNode,
    results: ApiEndpoint[],
  ): void {
    const rePathRe = new RegExp(DJANGO_RE_PATH_RE.source, DJANGO_RE_PATH_RE.flags);
    let match: RegExpExecArray | null;

    while ((match = rePathRe.exec(source)) !== null) {
      const regexPath = match[1] ?? '';
      const viewRef = (match[2] ?? '').trim();

      const handler = this.extractViewName(viewRef);
      const normalizedPath = this.normalizeRegexPath(regexPath);

      this.addEndpoint(results, 'GET', normalizedPath, handler, fileNode);
    }
  }

  // -------------------------------------------------------------------------
  // Private: @api_view endpoint extraction
  // -------------------------------------------------------------------------

  /**
   * 從 @api_view decorator 提取 DRF function-based view 端點。
   *
   * 解析 `@api_view(['GET', 'POST'])` 中的 HTTP methods，
   * 然後在下方找到 `def` 行以取得 handler 名稱。
   *
   * @param source 檔案原始碼
   * @param fileNode 檔案 GraphNode
   * @param results 收集端點的目標陣列
   */
  private extractApiViewEndpoints(
    source: string,
    fileNode: GraphNode,
    results: ApiEndpoint[],
  ): void {
    const apiViewRe = new RegExp(DRF_API_VIEW_RE.source, DRF_API_VIEW_RE.flags);
    const sourceLines = source.split('\n');
    let match: RegExpExecArray | null;

    while ((match = apiViewRe.exec(source)) !== null) {
      const methodListStr = match[1] ?? '';

      // Parse HTTP methods from the list: ['GET', 'POST'] -> ['GET', 'POST']
      const methods = this.parseApiViewMethods(methodListStr);
      if (methods.length === 0) continue;

      // Find handler function name from next def line (within 5 lines)
      const decoratorOffset = match.index;
      const lineIdx = source.substring(0, decoratorOffset).split('\n').length;
      let handlerName = '<anonymous>';

      for (let i = lineIdx; i < Math.min(lineIdx + 5, sourceLines.length); i++) {
        const defMatch = PythonBaseAdapter.PYTHON_DEF_RE.exec(sourceLines[i] ?? '');
        if (defMatch) {
          handlerName = defMatch[1] ?? '<anonymous>';
          break;
        }
      }

      // Generate one endpoint per HTTP method
      for (const method of methods) {
        const endpointPath = `/${handlerName}`;
        this.addEndpoint(results, method, endpointPath, handlerName, fileNode);
      }
    }
  }

  // -------------------------------------------------------------------------
  // Private: ViewSet endpoint extraction
  // -------------------------------------------------------------------------

  /**
   * 從 ViewSet class 定義產生標準 CRUD 端點。
   *
   * 支援：
   *   - `ModelViewSet` -> list / create / retrieve / update / destroy
   *   - `ReadOnlyModelViewSet` -> list / retrieve
   *   - `ViewSet` / `GenericViewSet` -> list
   *
   * @param source 檔案原始碼
   * @param fileNode 檔案 GraphNode
   * @param results 收集端點的目標陣列
   */
  private extractViewSetEndpoints(
    source: string,
    fileNode: GraphNode,
    results: ApiEndpoint[],
  ): void {
    const viewSetRe = new RegExp(DRF_VIEWSET_RE.source, DRF_VIEWSET_RE.flags);
    let match: RegExpExecArray | null;

    while ((match = viewSetRe.exec(source)) !== null) {
      const className = match[1] ?? '';
      const parentClass = match[2] ?? '';

      // Derive a URL base from the class name: UserViewSet -> /users
      const basePath = this.viewSetToBasePath(className);

      // Select CRUD set based on parent class
      let crudEntries: ViewSetCrudEntry[];
      switch (parentClass) {
        case 'ModelViewSet':
          crudEntries = MODEL_VIEWSET_CRUD;
          break;
        case 'ReadOnlyModelViewSet':
          crudEntries = READONLY_VIEWSET_CRUD;
          break;
        case 'ViewSet':
        case 'GenericViewSet':
          crudEntries = GENERIC_VIEWSET_CRUD;
          break;
        default:
          crudEntries = GENERIC_VIEWSET_CRUD;
      }

      for (const entry of crudEntries) {
        const fullPath = `${basePath}${entry.suffix}`;
        const handler = `${className}.${entry.action}`;
        this.addEndpoint(results, entry.method, fullPath, handler, fileNode);
      }
    }
  }

  // -------------------------------------------------------------------------
  // Private: helpers
  // -------------------------------------------------------------------------

  /**
   * 從 view reference 字串中提取 view 函式或 class 名稱。
   *
   * 處理常見模式：
   *   - `views.user_list` -> `user_list`
   *   - `user_list` -> `user_list`
   *   - `UserListView.as_view()` -> `UserListView`
   *
   * @param viewRef 原始 view 引用字串
   * @returns 提取的 view 名稱
   */
  private extractViewName(viewRef: string): string {
    const trimmed = viewRef.trim();

    // Handle as_view() pattern
    const asViewMatch = AS_VIEW_RE.exec(trimmed);
    if (asViewMatch) {
      AS_VIEW_RE.lastIndex = 0;
      return asViewMatch[1] ?? trimmed;
    }
    // Reset regex state
    AS_VIEW_RE.lastIndex = 0;

    // Handle dotted reference: views.user_list -> user_list
    const dotIdx = trimmed.lastIndexOf('.');
    if (dotIdx !== -1) {
      return trimmed.substring(dotIdx + 1);
    }

    // Plain function name
    return trimmed;
  }

  /**
   * 正規化 Django path() URL 路徑。
   *
   * - 確保路徑以 `/` 開頭
   * - 將 Django path converters `<int:pk>` 轉為 `:pk`
   *
   * @param urlPath 原始 URL path 字串
   * @returns 正規化後的路徑
   */
  private normalizeDjangoPath(urlPath: string): string {
    let normalized = urlPath;

    // Ensure leading slash
    if (!normalized.startsWith('/')) {
      normalized = `/${normalized}`;
    }

    // Convert Django path converters: <int:pk> -> :pk, <str:slug> -> :slug, <pk> -> :pk
    normalized = normalized.replace(/<(?:\w+:)?(\w+)>/g, ':$1');

    return normalized;
  }

  /**
   * 正規化 Django re_path() regex URL 路徑。
   *
   * - 移除 regex 錨點 `^` 和 `$`
   * - 將 named groups `(?P<pk>[0-9]+)` 轉為 `:pk`
   * - 確保路徑以 `/` 開頭
   *
   * @param regexPath 原始 regex path 字串
   * @returns 正規化後的路徑
   */
  private normalizeRegexPath(regexPath: string): string {
    let normalized = regexPath;

    // Remove regex anchors
    normalized = normalized.replace(/^\^/, '').replace(/\$$/, '');

    // Convert named groups: (?P<pk>[0-9]+) -> :pk
    normalized = normalized.replace(/\(\?P<(\w+)>[^)]*\)/g, ':$1');

    // Remove remaining regex character classes and quantifiers for readability
    normalized = normalized.replace(/\[[^\]]*\]\+?/g, '');

    // Ensure leading slash
    if (!normalized.startsWith('/')) {
      normalized = `/${normalized}`;
    }

    return normalized;
  }

  /**
   * 從 @api_view 的方法列表字串中解析 HTTP methods。
   *
   * @param methodListStr 方法列表字串（如 `'GET', 'POST'`）
   * @returns 正規化的 HttpMethod 陣列
   */
  private parseApiViewMethods(methodListStr: string): HttpMethod[] {
    const methods: HttpMethod[] = [];

    // Match quoted strings: 'GET', "POST"
    const methodRe = /['"](\w+)['"]/g;
    let match: RegExpExecArray | null;

    while ((match = methodRe.exec(methodListStr)) !== null) {
      const method = this.normaliseMethod(match[1] ?? '');
      if (method && !methods.includes(method)) {
        methods.push(method);
      }
    }

    return methods;
  }

  /**
   * 將 ViewSet class 名稱轉為 URL 基礎路徑。
   *
   * 轉換規則：
   *   - 移除 `ViewSet` 後綴
   *   - PascalCase 轉 kebab-case 後轉為複數形式
   *
   * @example `UserViewSet` -> `/users`
   * @example `ArticleCategoryViewSet` -> `/article-categories`
   *
   * @param className ViewSet class 名稱
   * @returns URL 基礎路徑（以 `/` 開頭）
   */
  private viewSetToBasePath(className: string): string {
    // Remove ViewSet suffix
    let name = className.replace(/ViewSet$/, '');

    // PascalCase to kebab-case
    name = name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

    // Simple pluralization: add 's' if not already ending in 's'
    if (!name.endsWith('s')) {
      name = `${name}s`;
    }

    return `/${name}`;
  }

  /**
   * 新增端點到結果陣列（去重）。
   *
   * @param results 目標陣列
   * @param method HTTP method
   * @param urlPath URL 路徑
   * @param handler handler 名稱
   * @param fileNode 檔案 GraphNode
   */
  private addEndpoint(
    results: ApiEndpoint[],
    method: HttpMethod,
    urlPath: string,
    handler: string,
    fileNode: GraphNode,
  ): void {
    const id = `${method} ${urlPath}`;

    // Deduplicate
    if (results.some((e) => e.id === id)) return;

    results.push({
      id,
      method,
      path: urlPath,
      handler,
      handlerFileId: fileNode.id,
    });
  }
}
