/**
 * CodeAtlas Web — WikiPreviewPanel Component
 *
 * Right-side preview panel (300 px) that renders when a wiki node is selected
 * in WikiGraph.  Displays:
 *   - Node header: title + type badge + language badge
 *   - Rendered markdown content (fetched from /api/wiki/page/:slug)
 *   - Three-perspective jump buttons (SF / LO / DJ) parsed from HTML comments
 *   - AI Deep Analysis trigger button with polling
 *
 * Design reference: proposal/references/sprint19/wiki-graph-mockup.html
 * (Scene 2 — MD Preview Panel)
 *
 * Sprint 19 — T14: MD Preview Panel + AI Analysis Button
 */

import {
  useEffect,
  useState,
  useCallback,
  useRef,
  type MouseEvent,
} from 'react';
import { fetchWikiPage } from '../api/wiki';
import { getAIJob } from '../api/graph';
import { useViewStateDispatch } from '../contexts/ViewStateContext';
import { THEME } from '../styles/theme';
import type { WikiSimNode, WikiPageDetail, WikiNodeType } from '../types/wiki';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const PANEL_WIDTH = 300;

/** Colour per node type — matches WikiGraph NODE_COLORS */
const TYPE_BADGE_STYLES: Record<WikiNodeType, { background: string; color: string }> = {
  architecture: { background: 'rgba(21,101,192,0.10)',  color: '#1565c0' },
  pattern:      { background: 'rgba(123,31,162,0.10)', color: '#7b1fa2' },
  feature:      { background: 'rgba(46,125,50,0.10)',  color: '#2e7d32' },
  integration:  { background: 'rgba(245,158,11,0.10)', color: '#b45309' },
  concept:      { background: 'rgba(0,131,143,0.10)',  color: '#00838f' },
};

/** Type icon (unicode) per node type */
const TYPE_ICONS: Record<WikiNodeType, string> = {
  architecture: '\uD83C\uDFD7\uFE0F', // 🏗️
  pattern:      '\uD83D\uDD04',        // 🔄
  feature:      '\u26A1',              // ⚡
  integration:  '\uD83D\uDD17',        // 🔗
  concept:      '\uD83D\uDCA1',        // 💡
};

/** Poll interval for AI job status (ms) */
const AI_POLL_INTERVAL_MS = 2000;

// ---------------------------------------------------------------------------
// Simple markdown → HTML renderer
// ---------------------------------------------------------------------------

/**
 * Renders a subset of Markdown syntax to an HTML string.
 * Does NOT use dangerouslySetInnerHTML on untrusted content — the wiki
 * pages are generated by the local CLI from the user's own codebase.
 */
function renderSimpleMarkdown(md: string): string {
  return md
    // Strip YAML frontmatter
    .replace(/^---[\s\S]*?---\n/, '')
    // Strip HTML comments (anchors were already parsed)
    .replace(/<!--[\s\S]*?-->/g, '')
    // Code blocks (``` ... ```)
    .replace(/```[\s\S]*?```/g, (block) => {
      const inner = block.replace(/^```[^\n]*\n/, '').replace(/```$/, '');
      return `<pre class="wp-codeblock"><code>${escapeHtml(inner.trimEnd())}</code></pre>`;
    })
    // Inline code
    .replace(/`([^`]+)`/g, '<code class="wp-inline-code">$1</code>')
    // Headers
    .replace(/^### (.+)$/gm, '<h3 class="wp-h3">$1</h3>')
    .replace(/^## (.+)$/gm, '<h2 class="wp-h2">$1</h2>')
    .replace(/^# (.+)$/gm, '<h1 class="wp-h1">$1</h1>')
    // Bold + italic
    .replace(/\*\*\*(.+?)\*\*\*/g, '<strong><em>$1</em></strong>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    // Wiki-links: [[slug|name]] → anchor with data-slug, blue underline per mockup
    .replace(/\[\[([^\]|]+)\|([^\]]+)\]\]/g, '<a class="wp-wiki-link" data-slug="$1" href="#" style="color:#1976d2;text-decoration:underline;cursor:pointer;">$2</a>')
    .replace(/\[\[([^\]]+)\]\]/g, '<a class="wp-wiki-link" data-slug="$1" href="#" style="color:#1976d2;text-decoration:underline;cursor:pointer;">$1</a>')
    // Unordered list items
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    // Paragraph breaks
    .replace(/\n\n/g, '</p><p class="wp-para">');
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

export interface WikiPreviewPanelProps {
  /** The selected wiki graph node; null = empty state */
  selectedNode: WikiSimNode | null;
  /** All nodes in the graph — used for wiki-link navigation */
  allNodes: WikiSimNode[];
  /** Callback to select a node from the panel (wiki-link click) */
  onSelectNode: (slug: string | null) => void;
}

// ---------------------------------------------------------------------------
// AI analysis state
// ---------------------------------------------------------------------------

type AiStatus = 'idle' | 'analyzing' | 'succeeded' | 'failed';

// ---------------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------------

function EmptyState() {
  return (
    <div style={styles.emptyWrap}>
      <div style={styles.emptyIcon} aria-hidden="true">&#x1F4DA;</div>
      <p style={styles.emptyTitle}>選取節點以預覽</p>
      <p style={styles.emptyBody}>在左側圖譜點選任一節點，即可在此查看詳細說明。</p>
    </div>
  );
}

function Skeleton() {
  return (
    <div style={styles.skeletonWrap} aria-label="載入中">
      {[80, 100, 65, 100, 55, 90].map((pct, i) => (
        <div
          key={i}
          style={{ ...styles.skeletonLine, width: `${pct}%`, animationDelay: `${i * 0.07}s` }}
        />
      ))}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------

export function WikiPreviewPanel({
  selectedNode,
  allNodes,
  onSelectNode,
}: WikiPreviewPanelProps) {
  const dispatch = useViewStateDispatch();

  // Page detail fetch state
  const [page, setPage] = useState<WikiPageDetail | null>(null);
  const [isFetching, setIsFetching] = useState(false);
  const [fetchError, setFetchError] = useState<string | null>(null);

  // AI analysis state
  const [aiStatus, setAiStatus] = useState<AiStatus>('idle');
  const [aiError, setAiError] = useState<string | null>(null);
  const pollTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // ---------------------------------------------------------------------------
  // Fetch page when node changes
  // ---------------------------------------------------------------------------

  useEffect(() => {
    if (!selectedNode) {
      setPage(null);
      setFetchError(null);
      setAiStatus('idle');
      setAiError(null);
      return;
    }

    let cancelled = false;
    setIsFetching(true);
    setFetchError(null);

    fetchWikiPage(selectedNode.slug)
      .then((detail) => {
        if (cancelled) return;
        if (detail === null) {
          setFetchError('無法載入頁面內容');
        } else {
          setPage(detail);
        }
        setIsFetching(false);
      })
      .catch(() => {
        if (!cancelled) {
          setFetchError('網路錯誤');
          setIsFetching(false);
        }
      });

    return () => { cancelled = true; };
  }, [selectedNode]);

  // ---------------------------------------------------------------------------
  // AI polling helpers
  // ---------------------------------------------------------------------------

  const clearPoll = useCallback(() => {
    if (pollTimerRef.current !== null) {
      clearTimeout(pollTimerRef.current);
      pollTimerRef.current = null;
    }
  }, []);

  const pollJob = useCallback(
    (jobId: string) => {
      clearPoll();
      pollTimerRef.current = setTimeout(async () => {
        try {
          const res = await getAIJob(jobId);
          const status = res.job.status;

          if (status === 'succeeded' || status === 'cached') {
            setAiStatus('succeeded');
            // Re-fetch page to show updated AI content
            if (selectedNode) {
              const updated = await fetchWikiPage(selectedNode.slug);
              if (updated) setPage(updated);
            }
          } else if (status === 'failed' || status === 'canceled') {
            setAiStatus('failed');
            setAiError('AI 分析失敗，請稍後再試。');
          } else {
            // Still running — poll again
            setAiStatus('analyzing');
            pollJob(jobId);
          }
        } catch {
          setAiStatus('failed');
          setAiError('AI 分析發生錯誤。');
        }
      }, AI_POLL_INTERVAL_MS);
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [clearPoll, selectedNode],
  );

  // Clean up timer on unmount
  useEffect(() => () => clearPoll(), [clearPoll]);

  // ---------------------------------------------------------------------------
  // AI analysis trigger
  // ---------------------------------------------------------------------------

  const handleAiAnalyze = useCallback(async () => {
    if (!selectedNode || aiStatus === 'analyzing') return;

    setAiStatus('analyzing');
    setAiError(null);

    try {
      const res = await fetch('/api/wiki/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ slug: selectedNode.slug }),
      });

      if (!res.ok) {
        setAiStatus('failed');
        setAiError(`伺服器錯誤 (${res.status})`);
        return;
      }

      let data: { jobId?: string };
      try {
        data = await res.json() as { jobId?: string };
      } catch {
        setAiStatus('failed');
        setAiError('無法解析伺服器回應');
        return;
      }

      if (!data.jobId) {
        setAiStatus('failed');
        setAiError('伺服器未回傳 jobId');
        return;
      }

      pollJob(data.jobId);
    } catch {
      setAiStatus('failed');
      setAiError('網路請求失敗');
    }
  }, [selectedNode, aiStatus, pollJob]);

  // ---------------------------------------------------------------------------
  // Wiki-link click — navigate within the graph
  // ---------------------------------------------------------------------------

  const handleContentClick = useCallback(
    (e: MouseEvent<HTMLDivElement>) => {
      const target = e.target as HTMLElement;
      if (target.classList.contains('wp-wiki-link')) {
        e.preventDefault();
        const slug = target.getAttribute('data-slug');
        if (slug) {
          const exists = allNodes.some((n) => n.slug === slug);
          if (exists) {
            onSelectNode(slug);
            dispatch({ type: 'SET_WIKI_NODE', slug });
          }
        }
      }
    },
    [allNodes, onSelectNode, dispatch],
  );

  // ---------------------------------------------------------------------------
  // Close panel
  // ---------------------------------------------------------------------------

  const handleClose = useCallback(() => {
    onSelectNode(null);
    dispatch({ type: 'SET_WIKI_NODE', slug: null });
  }, [onSelectNode, dispatch]);

  // ---------------------------------------------------------------------------
  // Render: nothing selected
  // ---------------------------------------------------------------------------

  if (!selectedNode) {
    return (
      <div style={styles.panel} aria-label="Wiki 預覽面板">
        <EmptyState />
      </div>
    );
  }

  // ---------------------------------------------------------------------------
  // Derive rendered content
  // ---------------------------------------------------------------------------

  const rawMd = page?.content ?? '';
  const renderedHtml = rawMd ? renderSimpleMarkdown(rawMd) : '';
  const wrappedHtml = `<p class="wp-para">${renderedHtml}</p>`;

  const typeBadgeStyle = TYPE_BADGE_STYLES[selectedNode.type] ?? TYPE_BADGE_STYLES.concept;
  const typeIcon = TYPE_ICONS[selectedNode.type] ?? '\uD83D\uDCA1';

  // ---------------------------------------------------------------------------
  // Render: panel with content
  // ---------------------------------------------------------------------------

  return (
    <div style={styles.panel} aria-label="Wiki 預覽面板">
      {/* ── Header ── */}
      <div style={styles.header}>
        <div style={styles.headerLeft}>
          <span style={styles.typeIcon} aria-hidden="true">{typeIcon}</span>
          <span style={styles.nodeName} title={selectedNode.displayName}>
            {selectedNode.displayName}
          </span>
        </div>
        <button
          type="button"
          style={styles.closeBtn}
          onClick={handleClose}
          aria-label="關閉預覽"
          title="關閉"
        >
          &#x2715;
        </button>
      </div>

      {/* ── Badges ── */}
      <div style={styles.badges}>
        <span
          style={{
            ...styles.badge,
            background: typeBadgeStyle.background,
            color: typeBadgeStyle.color,
          }}
        >
          {selectedNode.type}
        </span>
        {page?.hasAiContent && (
          <span style={styles.aiBadge} title="已有 AI 分析內容">✨ AI</span>
        )}
      </div>

      {/* ── YAML Frontmatter ── */}
      {selectedNode && (
        <div style={styles.frontmatterSection}>
          <p style={styles.frontmatterLabel}>YAML FRONTMATTER</p>
          <pre style={styles.frontmatterCode}>
            <code>{`concept: ${selectedNode.displayName}\ntype: ${selectedNode.type}${selectedNode.sourceFiles && selectedNode.sourceFiles.length > 0 ? `\nsources:\n${selectedNode.sourceFiles.map(f => `  - ${f}`).join('\n')}` : ''}`}</code>
          </pre>
        </div>
      )}

      {/* ── Markdown content ── */}
      <div style={styles.contentSection}>
        {isFetching ? (
          <Skeleton />
        ) : fetchError ? (
          <p style={styles.errorText}>{fetchError}</p>
        ) : page ? (
          <div
            style={styles.mdContent}
            // eslint-disable-next-line react/no-danger
            dangerouslySetInnerHTML={{ __html: wrappedHtml }}
            onClick={handleContentClick}
          />
        ) : (
          <p style={styles.emptyBodySmall}>無內容</p>
        )}
      </div>

      {/* ── Source files ── */}
      {selectedNode.sourceFiles && selectedNode.sourceFiles.length > 0 && (
        <div style={styles.sourceFilesSection}>
          <p style={styles.sectionTitle}>相關程式碼</p>
          {selectedNode.sourceFiles.map((f) => (
            <p key={f} style={styles.sourceFileItem}>{f}</p>
          ))}
        </div>
      )}

      {/* ── AI Analysis button ── */}
      <div style={styles.aiSection}>
        {aiStatus === 'idle' || aiStatus === 'failed' ? (
          <>
            <button
              type="button"
              style={styles.aiBtn}
              onClick={() => { void handleAiAnalyze(); }}
              disabled={isFetching}
            >
              &#x2728; AI 深度分析
            </button>
            {aiStatus === 'failed' && aiError && (
              <p style={styles.aiErrorText}>{aiError}</p>
            )}
          </>
        ) : aiStatus === 'analyzing' ? (
          <div style={styles.aiLoadingRow}>
            <div style={styles.aiSpinner} aria-hidden="true" />
            <span style={styles.aiLoadingText}>AI 分析中，請稍候…</span>
          </div>
        ) : (
          /* succeeded */
          <div style={styles.aiSuccessRow}>
            <span style={styles.aiSuccessText}>&#x2728; claude</span>
            <span style={styles.aiSuccessDot}>&middot;</span>
            <span style={styles.aiSuccessTime}>剛才</span>
            <span style={styles.aiSuccessDot}>&middot;</span>
            <button
              type="button"
              style={styles.aiReanalyzeBtn}
              onClick={() => { setAiStatus('idle'); }}
            >
              &#x1F5A5;&#xFE0F; 重新分析
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const styles = {
  panel: {
    width: PANEL_WIDTH,
    flexShrink: 0,
    background: '#ffffff',
    borderLeft: `1px solid ${THEME.borderDefault}`,
    boxShadow: '-2px 0 8px rgba(0,0,0,0.06)',
    display: 'flex',
    flexDirection: 'column' as const,
    overflow: 'hidden',
    zIndex: 40,
    fontFamily: THEME.fontUi,
  },

  // ── Header ──
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 14px 10px',
    borderBottom: `1px solid #e8e8f0`,
    flexShrink: 0,
  },

  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    minWidth: 0,
    flex: 1,
  },

  typeIcon: {
    fontSize: 16,
    flexShrink: 0,
  },

  nodeName: {
    fontSize: 15,
    fontWeight: 700,
    color: THEME.inkPrimary,
    letterSpacing: '-0.01em',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },

  closeBtn: {
    background: 'transparent',
    border: 'none',
    fontSize: 14,
    color: THEME.inkMuted,
    cursor: 'pointer',
    padding: '2px 4px',
    borderRadius: 3,
    lineHeight: 1,
    flexShrink: 0,
    opacity: 0.6,
  } as React.CSSProperties,

  // ── Badges ──
  badges: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '6px 14px 8px',
    borderBottom: `1px solid #f0f0f4`,
    flexWrap: 'wrap' as const,
    flexShrink: 0,
  },

  badge: {
    fontSize: 10,
    fontWeight: 600,
    padding: '2px 7px',
    borderRadius: 10,
  } as React.CSSProperties,

  aiBadge: {
    fontSize: 10,
    fontWeight: 600,
    padding: '2px 7px',
    borderRadius: 10,
    background: 'rgba(245,158,11,0.10)',
    color: '#b45309',
  } as React.CSSProperties,

  // ── YAML Frontmatter ──
  frontmatterSection: {
    padding: '8px 14px',
    borderBottom: '1px solid #f0f0f4',
    flexShrink: 0,
  },

  frontmatterLabel: {
    fontSize: 9,
    fontWeight: 600,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.08em',
    color: THEME.inkMuted,
    marginBottom: 6,
    opacity: 0.7,
  } as React.CSSProperties,

  frontmatterCode: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 10,
    lineHeight: 1.6,
    color: THEME.inkSecondary,
    background: '#f5f5f8',
    borderRadius: 6,
    padding: '8px 10px',
    margin: 0,
    overflow: 'auto',
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-all' as const,
  } as React.CSSProperties,

  // ── Markdown content ──
  contentSection: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: '10px 14px',
    minHeight: 0,
  },

  mdContent: {
    fontSize: 12,
    lineHeight: 1.65,
    color: THEME.inkSecondary,
  } as React.CSSProperties,

  // ── Source files ──
  sourceFilesSection: {
    padding: '10px 14px',
    borderTop: `1px solid #f0f0f4`,
    flexShrink: 0,
  },

  sectionTitle: {
    fontSize: 10,
    fontWeight: 600,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.07em',
    color: THEME.inkMuted,
    marginBottom: 6,
    opacity: 0.8,
  },

  sourceFileItem: {
    fontSize: 10,
    fontFamily: THEME.fontMono,
    color: THEME.inkSecondary,
    marginBottom: 2,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  } as React.CSSProperties,

  // ── AI section ──
  aiSection: {
    padding: '10px 14px 14px',
    borderTop: `1px solid #f0f0f4`,
    flexShrink: 0,
  },

  aiBtn: {
    width: '100%',
    fontSize: 11,
    fontWeight: 500,
    padding: '7px 12px',
    borderRadius: THEME.radiusSm,
    border: '1px solid rgba(245,158,11,0.45)',
    background: 'rgba(245,158,11,0.06)',
    color: '#b45309',
    cursor: 'pointer',
    fontFamily: THEME.fontUi,
    textAlign: 'center' as const,
    transition: 'background 0.15s',
  } as React.CSSProperties,

  aiLoadingRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '4px 0',
  },

  aiSpinner: {
    width: 14,
    height: 14,
    border: '2px solid rgba(245,158,11,0.25)',
    borderTopColor: '#f59e0b',
    borderRadius: '50%',
    animation: 'spin 0.8s linear infinite',
    flexShrink: 0,
  } as React.CSSProperties,

  aiLoadingText: {
    fontSize: 11,
    color: THEME.inkMuted,
  },

  aiSuccessRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap' as const,
    fontSize: 11,
  },

  aiSuccessText: {
    fontSize: 11,
    color: THEME.inkSecondary,
  },

  aiReanalyzeBtn: {
    fontSize: 10,
    background: 'transparent',
    border: 'none',
    color: THEME.inkMuted,
    cursor: 'pointer',
    textDecoration: 'underline',
    padding: 0,
    fontFamily: THEME.fontUi,
  } as React.CSSProperties,

  aiSuccessDot: {
    fontSize: 11,
    color: THEME.inkFaint,
  } as React.CSSProperties,

  aiSuccessTime: {
    fontSize: 11,
    color: THEME.inkMuted,
  } as React.CSSProperties,

  aiErrorText: {
    fontSize: 10,
    color: '#c62828',
    marginTop: 4,
  },

  // ── Skeleton loading ──
  skeletonWrap: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 8,
    padding: '4px 0',
  },

  skeletonLine: {
    height: 10,
    background: 'linear-gradient(90deg, #f0f0f4 25%, #e8e8f0 50%, #f0f0f4 75%)',
    backgroundSize: '200% 100%',
    borderRadius: 4,
    animation: 'skeleton-shimmer 1.4s ease-in-out infinite',
  } as React.CSSProperties,

  // ── Empty states ──
  emptyWrap: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    padding: '24px 20px',
    textAlign: 'center' as const,
  },

  emptyIcon: {
    fontSize: 36,
    marginBottom: 12,
    opacity: 0.5,
  },

  emptyTitle: {
    fontSize: 14,
    fontWeight: 600,
    color: THEME.inkPrimary,
    marginBottom: 8,
  } as React.CSSProperties,

  emptyBody: {
    fontSize: 12,
    color: THEME.inkSecondary,
    lineHeight: 1.6,
  } as React.CSSProperties,

  emptyBodySmall: {
    fontSize: 12,
    color: THEME.inkMuted,
  } as React.CSSProperties,

  errorText: {
    fontSize: 12,
    color: '#c62828',
  } as React.CSSProperties,
} as const;
